[package]
name = "guessing-game"
version = "0.1.0"
edition = "2021"
authors = ["Breno Ramalho Lemes <breno@br-lemes.net>"]

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
